/********************************************************************************************************************************************************************************************************************************************************                          
NOTICE:

For five (5) years from 1/21/2020 the United States Government is granted for itself and others acting on its behalf a paid-up, nonexclusive, irrevocable worldwide license in this data to reproduce, prepare derivative works, and perform 
publicly and display publicly, by or on behalf of the Government. There is provision for the possible extension of the term of this license. Subsequent to that period or any extension granted, the United States Government is granted for itself
and others acting on its behalf a paid-up, nonexclusive, irrevocable worldwide license in this data to reproduce, prepare derivative works, distribute copies to the public, perform publicly and display publicly, and to permit others to do so. The
specific term of the license can be identified by inquiry made to National Technology and Engineering Solutions of Sandia, LLC or DOE.
 
NEITHER THE UNITED STATES GOVERNMENT, NOR THE UNITED STATES DEPARTMENT OF ENERGY, NOR NATIONAL TECHNOLOGY AND ENGINEERING SOLUTIONS OF SANDIA, LLC, NOR ANY OF THEIR EMPLOYEES, MAKES ANY WARRANTY, 
EXPRESS OR IMPLIED, OR ASSUMES ANY LEGAL RESPONSIBILITY FOR THE ACCURACY, COMPLETENESS, OR USEFULNESS OF ANY INFORMATION, APPARATUS, PRODUCT, OR PROCESS DISCLOSED, OR REPRESENTS THAT ITS USE WOULD
NOT INFRINGE PRIVATELY OWNED RIGHTS.
 
Any licensee of this software has the obligation and responsibility to abide by the applicable export control laws, regulations, and general prohibitions relating to the export of technical data. Failure to obtain an export control license or other 
authority from the Government may result in criminal liability under U.S. laws.
 
                                             (End of Notice)
*********************************************************************************************************************************************************************************************************************************************************/
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PeakMap.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.3.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\ICRP07\\DATA\\ICRP-07.RAD")]
        public string LIBRARY {
            get {
                return ((string)(this["LIBRARY"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\ICRP07\\DATA\\ICRP-07.NDX")]
        public string CHAINS {
            get {
                return ((string)(this["CHAINS"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public double LOWERELIMT {
            get {
                return ((double)(this["LOWERELIMT"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3000")]
        public double UPPERELIMIT {
            get {
                return ((double)(this["UPPERELIMIT"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>ENERGY,Energy,</string>
  <string>YIELD,Yield (%),</string>
  <string>TYPE,Type,</string>
  <string>EFFICIENCY,Efficiency (%),E3</string>
  <string>AREA,Area (cts),E3</string>
  <string>MDA,MDA (cts),E3</string>
  <string>MATCHED,Matched,</string>
  <string>PEAKNUM,Peak No.,F0</string>
  <string>DIFFERENCE,Diff,</string>
  <string>RELACTIVITY,Rel. Acitvity,E3</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection LINES {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["LINES"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Th-232,Np-237,U-238,U-235")]
        public string CHAINPARENT {
            get {
                return ((string)(this["CHAINPARENT"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>NAME,Name,</string>
  <string>SCORE,Score,</string>
  <string>NUCLIDE,Nuclide,</string>
  <string>HALF_LIFE,Half Life,</string>
  <string>HALF_LIFE_UNIT,Unit,</string>
  <string>ENERGY,Energy,</string>
  <string>YIELD,Yield (%),</string>
  <string>TYPE,Type,</string>
  <string>DIFFERENCE,Diff,</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection NUCLIDES {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["NUCLIDES"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>NAME,Name,</string>
  <string>NUCLIDE,Nuclide,</string>
  <string>HALF_LIFE,Half Life,</string>
  <string>HALF_LIFE_UNIT,Unit,</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection NUCLIDESLIBRARY {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["NUCLIDESLIBRARY"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1E-09")]
        public double LOWERYIELD {
            get {
                return ((double)(this["LOWERYIELD"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>ENERGY,Energy,</string>
  <string>YIELD,Yield (%),</string>
  <string>TYPE,Type,</string>
  <string>NAME,Name,</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection LINESLIBRARY {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["LINESLIBRARY"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>ID,No.,F0</string>
  <string>ENERGY,Energy,</string>
  <string>FWHM,FWHM,</string>
  <string>AREA,Area,E3</string>
  <string>CONTINUUM,Continuum,E3</string>
  <string>MATCHNAME,Id,</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection PEAKS {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["PEAKS"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>ID,No.,F0</string>\r\n  <string>MATCHNAME,Id,</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection PEAKSLIBRARY {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["PEAKSLIBRARY"]));
            }
        }
    }
}
