//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PeakMap.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.10.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\ICRP07\\DATA\\ICRP-07.RAD")]
        public string LIBRARY {
            get {
                return ((string)(this["LIBRARY"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\ICRP07\\DATA\\ICRP-07.NDX")]
        public string CHAINS {
            get {
                return ((string)(this["CHAINS"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public double LOWERELIMT {
            get {
                return ((double)(this["LOWERELIMT"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8000")]
        public double UPPERELIMIT {
            get {
                return ((double)(this["UPPERELIMIT"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Th-232,Np-237,U-238,U-235")]
        public string CHAINPARENT {
            get {
                return ((string)(this["CHAINPARENT"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>NAME,Name,</string>
  <string>SCORE,Score,</string>
  <string>NUCLIDE,Nuclide,</string>
  <string>HALF_LIFE,Half Life,</string>
  <string>HALF_LIFE_UNIT,Unit,</string>
  <string>ENERGY,Energy,</string>
  <string>YIELD,Yield (%),</string>
  <string>TYPE,Type,</string>
  <string>DIFFERENCE,Diff,</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection NUCLIDES {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["NUCLIDES"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>NAME,Name,</string>
  <string>NUCLIDE,Nuclide,</string>
  <string>HALF_LIFE,Half Life,</string>
  <string>HALF_LIFE_UNIT,Unit,</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection NUCLIDESLIBRARY {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["NUCLIDESLIBRARY"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1E-09")]
        public double LOWERYIELD {
            get {
                return ((double)(this["LOWERYIELD"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>ENERGY,Energy,</string>
  <string>YIELD,Yield (%),</string>
  <string>TYPE,Type,</string>
  <string>NAME,Name,</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection LINESLIBRARY {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["LINESLIBRARY"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>ID,No.,F0</string>
  <string>ENERGY,Energy,</string>
  <string>FWHM,FWHM,</string>
  <string>AREA,Area,E3</string>
  <string>CONTINUUM,Continuum,E3</string>
  <string>MATCHNAME,Id,</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection PEAKS {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["PEAKS"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>ID,No.,F0</string>\r\n  <string>MATCHNAME,Id,</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection PEAKSLIBRARY {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["PEAKSLIBRARY"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>ENERGY,Energy,</string>
  <string>YIELD,Yield (%),</string>
  <string>TYPE,Type,</string>
  <string>AREA,Area (cts),E3</string>
  <string>GTRMDA, &gt; MDA,E3</string>
  <string>MDA,MDA (cts),E3</string>
  <string>MATCHED,Matched,</string>
  <string>PEAKNUM,Peak No.,F0</string>
  <string>DIFFERENCE,Diff,</string>
  <string>RELACTIVITY,Rel. Acitvity,E3</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection LINES {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["LINES"]));
            }
        }
    }
}
